from .enums import DatasetSplit

# These numbers were generated by Label-Studio. 
# Training project url example: localhost:8080/projects/2/data  
SPLIT_TO_LABELSTUDIO_NAME = {
    DatasetSplit.TRAINING: "2",
    DatasetSplit.VALIDATION: "3",
    DatasetSplit.TESTING: "1",
}